# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cef20eb271739ecc8fa0456033229e292bd625c3967bf147507eef65dac7558ce6a70cb85dbf98ef2676d44b253ed93d3ba9d74d249e78bbab6cb53af324cc79

test:
  secret_key_base: b6e0b87f57cfcd3f25703660a3d892a65e6f56a5664f4614b8db94e30b9031393d0f6f7ed65650c7ae7cc5a5ad66ed89ee355538b30eb2a8e293ab817fbd0487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
